### ISSUE TITLE
Migrations are not executed, when ocr languages are missing (even using ocr-multilang mod)

### ISSUE THREAD

**Issue by darkmattercoder** [linuxserver/docker-paperless-ngx#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Today I discovered that my e-mail jobs were not executed while listed as successfully in the task overview. Also deleting or modifying rules or accounts for e-mails resulted in a server 500 error. In both cases, the log complained about a missing db table. 

Filing a bug in the paperless-ngx project (https://github.com/paperless-ngx/paperless-ngx/issues/936) about this lead to a better understanding what's going on here. 

Somehow when the lsio image in the `50-config` job finds an error (ocr language is not installed), it does not actually perform the migration steps.

The multilang ocr mod is applied after this script is being run. So probably the docker mod could be loaded earlier?

However once started with the missing ocr language disabled, the container successgfully performed the migrations. I can add the language through the dockermod again afterwards and apparently now it is all back to normal. 

Beside being not. Because now everytime you need the migrations, you have to temporarily disable the ocr multilang mod once.

------------------------------

## Expected Behavior

Migrations should be executed even when a missing ocr language is detected / the ocr multilang mod is enabled
```
[cont-init.d] 50-config: executing...
paperless-ngx    | No changes detected
paperless-ngx    | Operations to perform:
paperless-ngx    |   Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
paperless-ngx    | Running migrations:
paperless-ngx    |   No migrations to apply.
paperless-ngx    | [cont-init.d] 50-config: exited 0.
```
## Current Behavior

Migrations are not run: 
```
[cont-init.d] 50-config: executing... 
paperless-ngx    | SystemCheckError: System check identified some issues:
paperless-ngx    | 
paperless-ngx    | ERRORS:
paperless-ngx    | ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
paperless-ngx    | SystemCheckError: System check identified some issues:
paperless-ngx    | 
paperless-ngx    | ERRORS:
paperless-ngx    | ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
paperless-ngx    | [cont-init.d] 50-config: exited 0.
```
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** debian buster
**CPU architecture:** x86_64
**How docker service was installed:**

official repo
## Command used to create docker container (run/create/compose/screenshot)

```
env:
DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
OCRLANG=deu
USERMAP_UID=995
USERMAP_GID=995
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_FILENAME_FORMAT={correspondent}-{created_year}{created_month}{created_day}-{document_type}-{tag_list}
PAPERLESS_TIME_ZONE=Europe/Berlin

compose:
---
version: "2.1"
services:
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx
    container_name: paperless-ngx
    environment:
      - PUID=${USERMAP_UID}
      - PGID=${USERMAP_GID}
      - TZ=${PAPERLESS_TIME_ZONE}
      - PAPERLESS_TIME_ZONE=${PAPERLESS_TIME_ZONE}
      - DOCKER_MODS=${DOCKER_MODS}
      - OCRLANG=${OCRLANG}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_FILENAME_FORMAT=${PAPERLESS_FILENAME_FORMAT}
    volumes:
      - config:/config
      - data:/data
    ports:
      - 8001:8000
    restart: unless-stopped

```
## Docker logs

See in the bug report over at paperless-ngx, there is a full log
